name: cross browser testing

on:
  push: 
    branches:
     - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run docker-compose
        run: docker-compose up -d e2e-chrome e2e-firefox

